name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pylint coverage

    - name: Run Pylint
      run: |
        # Ejecutar Pylint y extraer el score
        SCORE=$(pylint src/**/*.py --rcfile=.pylintrc | grep -oP 'Your code has been rated at \K\d+\.\d+' || echo "0.00")
        echo "Pylint score: $SCORE"
        # Fallar si el score es menor a 8.20
        if (( $(echo "$SCORE < 8.20" | bc -l) )); then
          echo "Pylint score is below 8.20!"
          exit 1
        fi

    - name: Test with unittest and Coverage
      run: |
        coverage run -m unittest discover -v
        coverage report -m --fail-under=90
